# Sample workflow for building and deploying a Jekyll site to GitHub Pages
name: Test Building Website

on: [push, pull_request]

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build with 11ty
        run: npm install && npm run build
